source'https://github.com/yelon21/LTSpecs.git'#我们自己的私有spec仓库的地址
source'https://github.com/CocoaPods/Specs.git'#官方仓库的地址

target 'LTExtUIBase_Example' do
  pod 'LTExtUIBase', :path => '../'

  target 'LTExtUIBase_Tests' do
    inherit! :search_paths

    
  end
end
